### ISSUE TITLE
Phase 7 needs more time

### ISSUE THREAD

**Issue by brookeangel** [benmcderm/buildstarter#1]
Styling especially will probably take a while - I would give this phase 2 days. 

Regarding likes and comments: depending on how you want to implement them, you may just want to fetch likes using the show jbuilder template for projects & just store them along with their associated project. It could get tricky to keep things in sync if you choose to use separate stores. Let me know how you're thinking of displaying likes and comments and we can decide if this is the correct route for you to take.

**Comment by benmcderm** [comment]
Sounds good Brooke, I was thinking of just doing a Facebook like plugin form their site.

For comments, it would be cool to mimic Kickstarter's tabs:

<img width="665" alt="screen shot 2016-06-28 at 10 03 45 am" src="https://cloud.githubusercontent.com/assets/5704245/16425079/aa968c1e-3d17-11e6-9152-09b75170d756.png">
